name: Image From Feature Branch
on: 
  push:
    branches: 
      - '*/*'
jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build and Push
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          repository: kris9819/requesterr-api
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          hash=$(git log -1 --pretty=%!H)
          docker build -t ${{ env.repository }}:$hash .
          docker push kris9819/requesterr-api